import { Inter } from 'next/font/google';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Aladin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/public/favicon/favicon-16x16.png"
        ></link>
      </Head>
      <h1 className={styles.red}>Welcome to next</h1>
    </>
  );
}
